# Generated by Django 3.0 on 2019-12-21 15:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='key',
            field=models.CharField(default=uuid.UUID('719eb72a-17de-4f57-9f9d-6c3b7a42c7d8'), max_length=50, unique=True),
        ),
    ]
