# Generated by Django 3.0 on 2020-01-10 19:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20191221_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='key',
            field=models.CharField(default=uuid.UUID('6222df60-81d8-4538-ae1e-29855b04eaf2'), max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='user',
            unique_together={('username', 'key')},
        ),
    ]
