# Generated by Django 3.0 on 2020-01-12 14:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20200110_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='key',
            field=models.CharField(default=uuid.UUID('70b60b55-21bb-43c6-a91d-abaef0d42cc7'), max_length=50, unique=True),
        ),
    ]
