# Generated by Django 3.0 on 2020-01-23 18:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20200112_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='key',
            field=models.CharField(default=uuid.UUID('e5b8fe0a-8fb3-415c-82ff-7e347a84cf14'), max_length=50, unique=True),
        ),
    ]
