# Generated by Django 3.0 on 2020-01-23 18:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20200123_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='key',
            field=models.CharField(default=uuid.UUID('02776ada-bce4-446a-a4be-48cb55a0ccc2'), max_length=50, unique=True),
        ),
    ]
