# Generated by Django 3.0 on 2020-01-23 18:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20200123_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='key',
            field=models.CharField(default=uuid.UUID('bdb5bac6-4495-4905-a7a9-fd4a1c610c72'), max_length=50, unique=True),
        ),
    ]
