# Generated by Django 3.0 on 2020-01-10 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_auto_20191221_1549'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together={('form', 'question', 'option')},
        ),
    ]
