# Generated by Django 3.0 on 2020-01-23 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_auto_20200110_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='description',
            field=models.CharField(choices=[('Very bad', 'Very bad'), ('Bad', 'Bad'), ('Neutral', 'Neutral'), ('Good', 'Good'), ('Very good', 'Very good')], default='Neutral', max_length=15),
        ),
    ]
